services:
  - type: web
    name: gif-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    buildpacks:
      - https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git
